[build]
  command = "npm ci && npm run build"   # (התקנת תלויות + בילד)
  publish = "dist"                      # (תיקיית הפלט של Vite)

[build.environment]
  NODE_VERSION = "20.11.1"              # (מנעילות גרסת Node יציבה ל-Build)

# SPA: כל נתיב צד-לקוח חוזר ל-index.html (פתרון 404 ב-React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
