[build]
  # מנקה קבצים מקונפליקטים ואז בונה את האתר
  command = "npx strip-conflicts && npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.1"

# SPA redirect (React / Vite / Single Page App)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
