# ==============================================================================
#  הגדרות בנייה כלליות (Global Build Settings)
# ==============================================================================
[build]
  # פקודת הבנייה - רצף של פקודות לביצוע
  # 1. ניסיון לנקות קונפליקטים של מיזוג (merge conflicts) באופן אוטומטי.
  #    - מריץ סקריפט ייעודי אם קיים (מומלץ).
  #    - אם לא, משתמש ב-sed כגיבוי למחוק שורות קונפליקט (זהירות: עלול להיות מסוכן).
  # 2. התקנת תלויות נקייה ומדויקת באמצעות `npm ci` (מהיר ואמין יותר מ-`npm install`).
  # 3. הרצת תסריט הבנייה של הפרויקט.
  command = "( [ -f scripts/strip-conflicts.cjs ] && node scripts/strip-conflicts.cjs || (echo 'fallback: sed cleanup' && git ls-files -z | xargs -0 sed -i '/^<<<<<<< .*/d;/^=======$/d;/^>>>>>>> .*/d') ) && npm ci && npm run build"

  # תיקיית הפלט של הבנייה. לשנות בהתאם לפרויקט.
  # "dist" - נפוץ ב-Vite, SvelteKit.
  # "build" - נפוץ ב-Create React App.
  # "out" - נפוץ ב-Next.js (סטטי).
  publish = "dist"

# ==============================================================================
#  הגדרות סביבת הבנייה (Build Environment)
# ==============================================================================
[build.environment]
  # קביעת גרסת Node.js מדויקת. קריטי למניעת אי-תאימויות בין הסביבה המקומית לשרת.
  NODE_VERSION = "20.11.1"

  # הורדת אזהרות לרמת שגיאות (נפוץ ב-Create React App).
  # אם הבנייה נכשלת בגלל אזהרות, הגדרת משתנה זה ל-false יכולה לעזור.
  # CI = "false"

  # דגלים (flags) למנהל החבילות NPM.
  # שימושי מאוד לפתרון בעיות תלויות עמית (peer dependencies).
  # אם הבנייה נכשלת על שגיאות `EER_DEPS`, בטל את ההערה מהשורה הבאה:
  # NPM_FLAGS = "--legacy-peer-deps"

# ==============================================================================
#  הגדרות ניתוב מחדש (Redirects)
# ==============================================================================
# כלל ניתוב סטנדרטי עבור Single Page Application (SPA) כמו React, Vue, Angular.
# מוודא שכל בקשה שאינה לקובץ סטטי מגיעה ל-index.html כדי שה-Router בצד הלקוח יטפל בה.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
