[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.1"

# SPA redirect (React/Vite) – שכל כתובת תגיע ל-index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
