name: Netlify Preview (PR)
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

permissions:
  contents: read
  deployments: write

jobs:
  preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy Preview
        id: deploy
        run: |
          URL=$(npx netlify deploy --message "PR #${{ github.event.number }}" --dir=$( [[ -d dist ]] && echo dist || echo build ) | awk '/Website Draft URL:/ {print $4}')
          echo "url=$URL" >> $GITHUB_OUTPUT
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_HUGGING_FACE_TOKEN: ${{ secrets.VITE_HUGGING_FACE_TOKEN }}

      - name: Comment Preview URL
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: "✅ Netlify Preview: ${{ steps.deploy.outputs.url }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
